---
galaxy_info:
  author: Derek Smiley
  description: A Systems Administrator and Avid Homelabber
  company: Plumbus Labs
  license: GNU General Public License

  min_ansible_version: "2.4"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
        - bionic
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie

  galaxy_tags: []

dependencies: []
